export const middleOfRo = [24.9668, 45.9432];

export const weatherCodeDescriptions = {
  0: "Clear sky",
  1: "Mainly clear",
  2: "Partly cloudy",
  3: "Overcast",
  45: "Fog",
  48: "Depositing rime fog",
  51: "Light drizzle",
  53: "Moderate drizzle",
  55: "Dense drizzle",
  56: "Light freezing drizzle",
  57: "Dense freezing drizzle",
  61: "Slight rain",
  63: "Moderate rain",
  65: "Heavy rain",
  66: "Light freezing rain",
  67: "Heavy freezing rain",
  71: "Slight snow fall",
  73: "Moderate snow fall",
  75: "Heavy snow fall",
  77: "Snow grains",
  80: "Slight rain showers",
  81: "Moderate rain showers",
  82: "Violent rain showers",
  85: "Slight snow showers",
  86: "Heavy snow showers",
  95: "Thunderstorm (slight)",
  96: "Thunderstorm (slight hail)",
  99: "Thunderstorm (severe hail)",
};

export const weatherIconsCodeDescriptionsURL = {
  0: "/images/svg/a_1_sunny.svg",
  1: "/images/svg/a_4_night.svg",
  2: "/images/svg/b_1_partly_cloudy.svg",
  3: "/images/svg/b_2_cloudy.svg",
  45: "/images/svg/d_4_fog.svg",
  48: "/images/svg/d_4_fog.svg",
  51: "/images/svg/c_1_rainy.svg",
  53: "/images/svg/c_1_rainy.svg",
  55: "/images/svg/c_1_rainy.svg",
  56: "/images/svg/d_3_sleet.svg",
  57: "/images/svg/d_3_sleet.svg",
  61: "/images/svg/c_1_rainy.svg",
  63: "/images/svg/c_1_rainy.svg",
  65: "/images/svg/c_2_heavy_rain.svg",
  66: "/images/svg/d_3_sleet.svg",
  67: "/images/svg/d_3_sleet.svg",
  71: "/images/svg/d_1_snow.svg",
  73: "/images/svg/d_2_heavy_snow.svg",
  75: "/images/svg/d_2_heavy_snow.svg",
  77: "/images/svg/g_3_snowflake.svg",
  80: "/images/svg/c_1_rainy.svg",
  81: "/images/svg/c_2_heavy_rain.svg",
  82: "/images/svg/c_2_heavy_rain.svg",
  85: "/images/svg/d_1_snow.svg",
  86: "/images/svg/d_2_heavy_snow.svg",
  95: "/images/svg/c_4_lightning.svg",
  96: "/images/svg/c_4_lightning.svg",
  99: "/images/svg/c_4_lightning.svg",
};

export const RANDOM_CITIES = [
  "Paris",
  "Berlin",
  "Madrid",
  "Rome",
  "Vienna",
  "Amsterdam",
  "Prague",
  "Lisbon",
  "Athens",
  "Budapest",
  "Dublin",
  "Stockholm",
  "Bucuresti",
  "Helsinki",
  "Warsaw",
  "New York",
  "Kyoto",
  "Beijing",
  "Mumbai",
  "Sydney",
  "Bangkok",
  "Buenos Aires",
  "Mexico City",
  "Cairo",
  "Queenstown",
  "Rio de Janeiro",
  "Seoul",
  "Bangkok",
  "Toronto",
  "Singapore",
  "Istanbul",
  "San Francisco",
  "Palermo",
  "Cape Town",
  "Cartagena",
  "Tbilisi",
  "Hoi An",
  "Dubrovnik",
  "Sedona",
  "Chefchaouen",
  "Taipei",
  "Edinburgh",
];

export const citiesTranslations = {
  Roma: "Rome",
  Praha: "Prague",
  München: "Munich",
  Zürich: "Zurich",
  Wien: "Vienna",
  Moskva: "Moscow",
  Lisboa: "Lisbon",
  København: "Copenhagen",
  Genève: "Geneva",
  Montréal: "Montreal",
  香港: "Hong Kong",
  北京: "Beijing",
  İstanbul: "Istanbul",
  القاهرة: "Cairo",
  新加坡: "Singapore",
  Buenos_Aires: "Buenos Aires",
  Santiago: "Santiago",
  São_Paulo: "São Paulo",
  Rio_de_Janeiro: "Rio de Janeiro",
  Guadalajara: "Guadalajara",
  Tokyo: "Tokyo",
  "New York": "New York City",
  "Los Angeles": "Los Angeles",
  "San Francisco": "San Francisco",
  Vancouver: "Vancouver",
  Sydney: "Sydney",
  Melbourne: "Melbourne",
  Milan: "Milan",
  Florence: "Florence",
  Madrid: "Madrid",
  Barcelona: "Barcelona",
  Paris: "Paris",
  Berlin: "Berlin",
  Rome: "Rome",
  Lima: "Lima",
  Cairo: "Cairo",
  Dhaka: "Dhaka",
  Lagos: "Lagos",
  Jakarta: "Jakarta",
  "Kuala Lumpur": "Kuala Lumpur",
  Seoul: "Seoul",
  Bangkok: "Bangkok",
  Hanoi: "Hanoi",
  "Cape Town": "Cape Town",
  Abuja: "Abuja",
  Kinshasa: "Kinshasa",
  "Addis Ababa": "Addis Ababa",
  Riyadh: "Riyadh",
  Manila: "Manila",
  Mumbai: "Mumbai",
  Kolkata: "Kolkata",
  Chennai: "Chennai",
  Hyderabad: "Hyderabad",
  Karachi: "Karachi",
  Lahore: "Lahore",
  Abidjan: "Abidjan",
  Douala: "Douala",
  Bamako: "Bamako",
  Accra: "Accra",
  "Dar es Salaam": "Dar es Salaam",
  Nairobi: "Nairobi",
  Algiers: "Algiers",
  Casablanca: "Casablanca",
  Montevideo: "Montevideo",
  Asunción: "Asunción",
  Quito: "Quito",
  "La Paz": "La Paz",
  Guayaquil: "Guayaquil",
  Tegucigalpa: "Tegucigalpa",
  Porto: "Porto",
  Tangier: "Tangier",
  Amman: "Amman",
  Yerevan: "Yerevan",
  Belgrade: "Belgrade",
  Warsaw: "Warsaw",
  Skopje: "Skopje",
  Sofia: "Sofia",
  Riga: "Riga",
  Tallinn: "Tallinn",
  Vilnius: "Vilnius",
  Zagreb: "Zagreb",
  Podgorica: "Podgorica",
  Sarajevo: "Sarajevo",
  Chisinau: "Chisinau",
  Bucharest: "Bucharest",
};
